### ISSUE TITLE
'Top daily costly services' shows current month estimate

### ISSUE THREAD

**Issue by uriinf** [cboudereau/grafana-dashboards#10]
I noticed that the Pie chart panel 'Top daily costly services' shows the current month's estimated costs by service, rather than top daily costs. Shouldn't the panel be renamed to 'Top costly services (current month)'? Am I missing something?

**Comment by cboudereau** [comment]
Hi, thank you for this issue.

Yes, the title does not match with the query. The pie chart display the Gauge rather than the daily costs.

In #11 I updated two panels to display per period (per day/week/month) aggregation with a better title including the period used to aggregate metrics.

~~I'll publish a new version of this dashboard, but in the meantime, do not hesitate to import this dashboard from the source.~~

I pushed the new dashboard to grafana dashboards with the ID 20288

Do not hesitate to reopen the issue if you think that something is missing.
